import { Button, ButtonSize, ButtonVariant } from '@/z-shared/ui/button';
import Test from '@/z-shared/assets/icons/uil_fire.svg';
import { AccentColors } from '@/z-shared/types/appColors';
import s from './mainPage.module.scss';

const MainPage = () => (
    <div className={s['container']}>
        <div className={s['row']}>
            <Button
                variant={ButtonVariant.PRIMARY}
                text={'button'}
                icon={<Test/>}
                size={ButtonSize.S}
                secondaryIcon={<Test/>}
            />
            <Button
                variant={ButtonVariant.PRIMARY}
                theme={AccentColors.GREEN}
                text={'button'}
                icon={<Test/>}
            />
            <Button
                variant={ButtonVariant.PRIMARY}
                theme={AccentColors.RED}
                text={'button'}
                icon={<Test/>}
            />
            <Button
                variant={ButtonVariant.PRIMARY}
                theme={AccentColors.BLUE}
                text={'button'}
                icon={<Test/>}
            />
            <Button
                variant={ButtonVariant.PRIMARY}
                theme={AccentColors.ORANGE}
                text={'button'}
                icon={<Test/>}
            />
        </div>
        <div className={s['row']}>
            <Button
                variant={ButtonVariant.SECONDARY}
                text={'button'}
                icon={<Test/>}
                secondaryIcon={<Test/>}
            />
            <Button
                variant={ButtonVariant.SECONDARY}
                theme={AccentColors.GREEN}
                text={'button'}
                icon={<Test/>}
            />
            <Button
                variant={ButtonVariant.SECONDARY}
                theme={AccentColors.RED}
                text={'button'}
                icon={<Test/>}
            />
            <Button
                variant={ButtonVariant.SECONDARY}
                theme={AccentColors.BLUE}
                text={'button'}
                icon={<Test/>}
            />
            <Button
                variant={ButtonVariant.SECONDARY}
                theme={AccentColors.ORANGE}
                text={'button'}
                icon={<Test/>}
            />
        </div>
        <div className={s['row']}>
            <Button
                variant={ButtonVariant.FLAT}
                text={'button'}
                icon={<Test/>}
                secondaryIcon={<Test/>}
            />
            <Button
                variant={ButtonVariant.FLAT}
                theme={AccentColors.GREEN}
                text={'button'}
                icon={<Test/>}
            />
            <Button
                variant={ButtonVariant.FLAT}
                theme={AccentColors.RED}
                text={'button'}
                icon={<Test/>}
            />
            <Button
                variant={ButtonVariant.FLAT}
                theme={AccentColors.BLUE}
                text={'button'}
                icon={<Test/>}
            />
            <Button
                variant={ButtonVariant.FLAT}
                theme={AccentColors.ORANGE}
                text={'button'}
                icon={<Test/>}
            />
        </div>
        <div className={s['row']}>
            <Button
                variant={ButtonVariant.THIN}
                text={'button'}
                icon={<Test/>}
                secondaryIcon={<Test/>}
            />
            <Button
                variant={ButtonVariant.THIN}
                theme={AccentColors.GREEN}
                text={'button'}
                icon={<Test/>}
            />
            <Button
                variant={ButtonVariant.THIN}
                theme={AccentColors.RED}
                text={'button'}
                icon={<Test/>}
            />
            <Button
                variant={ButtonVariant.THIN}
                theme={AccentColors.BLUE}
                text={'button'}
                icon={<Test/>}
            />
            <Button
                variant={ButtonVariant.THIN}
                theme={AccentColors.ORANGE}
                text={'button'}
                icon={<Test/>}
            />
        </div>
        <div className={s['row']}>
            <Button
                variant={ButtonVariant.GHOST}
                text={'button'}
                icon={<Test/>}
                secondaryIcon={<Test/>}
            />
            <Button
                variant={ButtonVariant.GHOST}
                theme={AccentColors.GREEN}
                text={'button'}
                icon={<Test/>}
            />
            <Button
                variant={ButtonVariant.GHOST}
                theme={AccentColors.RED}
                text={'button'}
                icon={<Test/>}
            />
            <Button
                variant={ButtonVariant.GHOST}
                theme={AccentColors.BLUE}
                text={'button'}
                icon={<Test/>}
            />
            <Button
                variant={ButtonVariant.GHOST}
                theme={AccentColors.ORANGE}
                text={'button'}
                icon={<Test/>}
            />
        </div>
    </div>
);

export default MainPage;
