export enum AppTypography {
    H1 = 'h1',
    H2 = 'h2',
    H3 = 'h3',
    H4 = 'h4',
    H5 = 'h5',
    H6 = 'h6',
    TEXT = 'text',
    TEXT_BOLD = 'text-bold',
    SUBTITLE = 'subtitle',
    BTN_LABEL = 'button-label',
    BTN_LABEL_MINI = 'button-label-mini',
    CAPTION = 'caption',
    CAPTION_MINI = 'caption-mini',
}
